### ISSUE TITLE
Feature Request: support multiple archive files

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [s427/MARL#3]
Thanks for this! It's really great to have since there's no proper way to migrate posts in Mastodon (yet).

I've migrated servers multiple times, so I have more than one archive file. It would be cool to be able to view them all (merged) in the same page. Not super necessary but a nice to have.

**Comment by tinglycraniumplacidly** [comment]
Couple alternative ideas I had which I would also be happy with

1. the ability to reference the archive file in the URL. Not entirely sure if this would be possible, but that way I could just bookmark separate URLs for each of my archives.

2. If that's not possible, maybe a history of previously loaded archive files from the main page

**Comment by s427** [comment]
I don't think that would be possible. For security reasons, browsers are extremely restrictive when it comes to accessing the local filesystem. Basically, only the user can access and select local files. If scripts could do it, or if the process could be automated in any way, it would open the door to all kinds of abuses.

So displaying a list of the recently opened files (history) on the main page would certainly be feasible, but you couldn't _do_ anything with it. For instance, you could _not_ click on an item of the list and have the script automatically load that file for you. The browser doesn't allow scripts to access the local filesystem.

**Comment by s427** [comment]
The latest version now support opening multiple archive files simultaneously. :)

You can open multiple files from the "load" dialog, and you can also drag and drop one or several files on the MARL window at any point, even if other files are already loaded.

If a file is identical to a file that is already loaded, it will simply be ignored (not loaded).

Let me know if you find any issue.

**Comment by tinglycraniumplacidly** [comment]
wow, just tested. that's freaking amazing ❤️

**Comment by s427** [comment]
Thanks!
