### ISSUE TITLE
Store paging order as a user preference

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [s427/MARL#4]
Small request: I feel like sorting by "reverse paging" should be by default since this is the way timelines are listed on most platforms.

**Comment by s427** [comment]
I think this could be debated without end as there is no right or wrong answer. IMO exploring an archive is not the same experience as reading a timeline, so to me it makes more sense to have the posts sorted by chronological order. So I don't think I will change that.

However what I might consider is treating this option as a user preference, stored locally (in the browser). That way the app would remember your last setting and you wouldn't have to change it every time.

**Comment by tinglycraniumplacidly** [comment]
User preference would be great! thanks!

**Comment by tinglycraniumplacidly** [comment]
sick, you rule. thanks!
