### ISSUE TITLE
Images (attached media) won't load

### ISSUE THREAD

**Issue by Isocat** [s427/MARL#5]
Pics (attached media) don't load. My .zip is a 620mb file, and I'm on a mid-'15 Macbook Pro with 16gb RAM (and just barely enough free/swapspace on the 2TB SSD), running MacOS 12.7.6. Tried Orion, Safari, and Firefox, with same result in all browsers. Don't have another machine to try it on. 

Screen grab and Firefox logs (with seemingly-relevant error messages) attached.

![Screen Shot 2024-12-06 at 09 28 07](https://github.com/user-attachments/assets/6c6d33a3-dc71-4af2-83ca-1670a5e5ea1f)
[FF Console Log.txt](https://github.com/user-attachments/files/18070156/FF.Console.Log.txt)

**Comment by s427** [comment]
Thank you. I haven't seen this behavior before.

If you don't mind, could you also post the JSON data for one of those posts with attachment. For instance the "This is srsly impressive" post seen in your screenshot. You can find the JSON code by clicking on "Raw data" below the post.

**Comment by s427** [comment]
@Isocat Good news: another Mastonaut apparently had a similar issue and allowed me to examine his archive file. I've just now published a fix for it. I think it should apply to your problem also. Let me know if this is the case! (Or not!)

**Comment by Isocat** [comment]
@s427 Hey, lookit there! It's working correctly in Firefox. Not in Orion, as it seems, but I am still struggling with getting Orion to behave all the way correctly on a variety of websites, so that is likely an Orion problem. Thank you!

**Comment by s427** [comment]
That's good to hear. :) Except for Orion of course. I'm not on MacOS so I can't really look into that unfortunately, but feel free to let me know if you have more info about it.
I'm closing this issue in the meantime.
